# Generated by Django 5.2.7 on 2025-10-20 00:31

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite', models.CharField(choices=[('LANDSAT', 'Landsat'), ('SENTINEL2', 'Sentinel-2'), ('MODIS', 'MODIS'), ('SENTINEL1', 'Sentinel-1')], max_length=20)),
                ('image_id', models.CharField(help_text='Google Earth Engine image ID', max_length=255, unique=True)),
                ('acquisition_date', models.DateField(help_text='Date when the image was acquired')),
                ('cloud_cover', models.FloatField(help_text='Cloud cover percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('resolution', models.FloatField(help_text='Spatial resolution in meters')),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(help_text='Image bounds', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Satellite Image',
                'verbose_name_plural': 'Satellite Images',
                'ordering': ['-acquisition_date'],
            },
        ),
        migrations.CreateModel(
            name='VegetationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('NDVI', 'Normalized Difference Vegetation Index'), ('EVI', 'Enhanced Vegetation Index'), ('SAVI', 'Soil Adjusted Vegetation Index'), ('NDMI', 'Normalized Difference Moisture Index'), ('NBR', 'Normalized Burn Ratio'), ('NDWI', 'Normalized Difference Water Index'), ('GNDVI', 'Green Normalized Difference Vegetation Index'), ('OSAVI', 'Optimized Soil Adjusted Vegetation Index')], max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Description of what this index measures')),
                ('formula', models.TextField(help_text='Mathematical formula for the index')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vegetation Index',
                'verbose_name_plural': 'Vegetation Indices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AreaOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the area of interest', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the area', null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(help_text='Polygon geometry of the area', srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this area is actively monitored')),
                ('area_hectares', models.FloatField(blank=True, help_text='Area in hectares', null=True)),
                ('centroid_lat', models.FloatField(blank=True, help_text='Centroid latitude', null=True)),
                ('centroid_lon', models.FloatField(blank=True, help_text='Centroid longitude', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_of_interest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area of Interest',
                'verbose_name_plural': 'Areas of Interest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_value', models.FloatField(help_text='Mean value of the index for the area')),
                ('min_value', models.FloatField(help_text='Minimum value of the index for the area')),
                ('max_value', models.FloatField(help_text='Maximum value of the index for the area')),
                ('std_value', models.FloatField(help_text='Standard deviation of the index for the area')),
                ('pixel_count', models.IntegerField(help_text='Number of pixels in the area')),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('area_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_data', to='monitoring.areaofinterest')),
                ('satellite_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_data', to='monitoring.satelliteimage')),
                ('vegetation_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_data', to='monitoring.vegetationindex')),
            ],
            options={
                'verbose_name': 'Monitoring Data',
                'verbose_name_plural': 'Monitoring Data',
                'ordering': ['-calculation_date'],
                'unique_together': {('area_of_interest', 'vegetation_index', 'satellite_image')},
            },
        ),
        migrations.CreateModel(
            name='MonitoringAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('THRESHOLD_LOW', 'Value below threshold'), ('THRESHOLD_HIGH', 'Value above threshold'), ('CHANGE_DETECTED', 'Significant change detected'), ('ANOMALY', 'Anomaly detected')], max_length=20)),
                ('message', models.TextField(help_text='Alert message')),
                ('threshold_value', models.FloatField(blank=True, help_text='Threshold value that triggered the alert', null=True)),
                ('actual_value', models.FloatField(help_text='Actual value that triggered the alert')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('area_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.areaofinterest')),
                ('monitoring_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.monitoringdata')),
                ('vegetation_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.vegetationindex')),
            ],
            options={
                'verbose_name': 'Monitoring Alert',
                'verbose_name_plural': 'Monitoring Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether monitoring is enabled for this combination')),
                ('monitoring_frequency_days', models.IntegerField(default=30, help_text='How often to monitor in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('low_threshold', models.FloatField(blank=True, help_text='Low threshold for alerts', null=True)),
                ('high_threshold', models.FloatField(blank=True, help_text='High threshold for alerts', null=True)),
                ('change_threshold_percent', models.FloatField(blank=True, help_text='Percentage change threshold for alerts', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cloud_cover_threshold', models.FloatField(default=20, help_text='Maximum cloud cover percentage to use image', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_pixel_count', models.IntegerField(default=10, help_text='Minimum number of pixels required for analysis', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_of_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='monitoring.areaofinterest')),
                ('vegetation_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='monitoring.vegetationindex')),
            ],
            options={
                'verbose_name': 'Monitoring Configuration',
                'verbose_name_plural': 'Monitoring Configurations',
                'unique_together': {('area_of_interest', 'vegetation_index')},
            },
        ),
    ]
