# Generated by Django 5.2.7 on 2025-11-14 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the tip', max_length=255)),
                ('content', models.TextField(help_text='Content of the tip')),
                ('category', models.CharField(choices=[('irrigation', 'Irrigation'), ('fertilization', 'Fertilization'), ('pest_control', 'Pest Control'), ('harvesting', 'Harvesting'), ('soil_health', 'Soil Health'), ('crop_rotation', 'Crop Rotation'), ('general', 'General')], default='general', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL for the tip', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tip is active')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tip',
                'verbose_name_plural': 'Tips',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='areaofinterest',
            name='crop_type',
            field=models.CharField(blank=True, choices=[('wheat', 'Wheat'), ('corn', 'Corn'), ('rice', 'Rice'), ('soybean', 'Soybean'), ('cotton', 'Cotton'), ('sugar_cane', 'Sugar Cane'), ('potato', 'Potato'), ('tomato', 'Tomato'), ('barley', 'Barley'), ('sorghum', 'Sorghum'), ('millet', 'Millet'), ('other', 'Other')], help_text='Type of crop grown in this area', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='areaofinterest',
            name='expected_harvest_date',
            field=models.DateField(blank=True, help_text='Expected harvest date', null=True),
        ),
        migrations.AddField(
            model_name='areaofinterest',
            name='planting_date',
            field=models.DateField(blank=True, help_text='Date when crop was planted', null=True),
        ),
        migrations.AddField(
            model_name='areaofinterest',
            name='soil_type',
            field=models.CharField(blank=True, help_text='Soil type classification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monitoringdata',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='Date when satellite image was acquired', null=True),
        ),
        migrations.AddField(
            model_name='monitoringdata',
            name='predicted_yield',
            field=models.FloatField(blank=True, help_text='Predicted crop yield in tons/hectare based on vegetation indices', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='monitoringdata',
            name='yield_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score for yield prediction (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='areaofinterest',
            name='name',
            field=models.CharField(help_text='Name of the farm/field', max_length=255),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='name',
            field=models.CharField(choices=[('NDVI', 'Normalized Difference Vegetation Index'), ('EVI', 'Enhanced Vegetation Index'), ('SAVI', 'Soil Adjusted Vegetation Index'), ('NDMI', 'Normalized Difference Moisture Index'), ('NBR', 'Normalized Burn Ratio'), ('NDWI', 'Normalized Difference Water Index'), ('GNDVI', 'Green Normalized Difference Vegetation Index'), ('OSAVI', 'Optimized Soil Adjusted Vegetation Index'), ('LAI', 'Leaf Area Index'), ('NDRE', 'Normalized Difference Red Edge'), ('CIRE', 'Chlorophyll Index Red Edge')], max_length=10, unique=True),
        ),
    ]
